### PR TITLE
Remove unused dependencies, add browser build

### PR DESCRIPTION
**Pull request by g-a-v-i-n**
- lodash was never tree shaken, so this lib was 78% lodash. I removed most methods in favor of builtins
- I kept chunk and isEqual, but imported them slightly differently
- I added build automation. The current version requires a build tool downstream, and now it does not. It doesn't require transpilation, only import resolution and node conversion.

This could be improved by
- adding `gulp` to travis to ensure build works
- should prob update the changelog

### CODE REVIEW

**Comment by jtobin** [comment]
Also, re: the CHANGELOG -- don't worry about that.  I usually just bump that manually when I make a release (i.e. tag commit, publish to npm).

**Comment by g-a-v-i-n** [comment]
You should be able to load the browser build anywhere else, even in node. I added the browser entry to package.json anyway.

- added `npm run build` in package.json
- removed most comments. Left documentation comment in gulpfile
- updated changelog, I kind of like this actually
-

**Comment by g-a-v-i-n** [comment]
Also, ob-js should be updated in urbit-keygen-js. I can do this but will need @jtobin to release ob-js to npm first

**Comment by jtobin** [comment]
(Just FYI, back from vacation tomorrow, will rebase/merge/release/publish then.)

**Comment by jtobin** [comment]
I wound up tweaking this a bit -- gulp doesn't add anything here over plain old rollup, so I whittled the build down to solely use that.  There were also a few unused dependencies/rollup plugins, so I axed those as well (I made sure to verify that the build produced was exactly the same).

**Comment by jtobin** [comment]
> Also, WTF was I thinking when I wrote Object.assign(.. like that.. 🤔

It turns out I was thinking correctly -- deleting this totally changed the library's API downstream.. 😄

**Pull request merged**
